pages/urls.py
from django.urls import path

from .views import HomePageView, AboutPageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutPageView.as_view(), name='about'),
]

widget_collection/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("django.contrib.auth.urls")),
    path("accounts/", include("allauth.urls")),
    path("pages/", include("pages.urls")),
    path("", include("widgets.urls", namespace="widgets")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

widgets/urls.py
from django.urls import path

from widgets.views import (
    WidgetListView,
    WidgetDetailView,
    CommentCreateView,
    CommentUpdateView,
    CommentDeleteView,
)

app_name = "widgets"

urlpatterns = [
    path("", WidgetListView.as_view(), name="index"),
    path("<uuid:pk>", WidgetDetailView.as_view(), name="detail"),
    path("<uuid:pk>/create", CommentCreateView.as_view(), name="comment_create"),
    path("<uuid:pk>/update", CommentUpdateView.as_view(), name="comment_update"),
    path("<uuid:pk>/delete", CommentDeleteView.as_view(), name="comment_delete"),
]

pages/models.py
from django.db import models

# Create your models here.

users/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.email

widgets/models.py
import uuid

from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model


class BaseModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Widget(BaseModel):
    name = models.CharField(max_length=256)
    curator = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="widgets"
    )

    class Meta:
        permissions = [("curator", "create update and delete widgets")]
        ordering = ["-created_at"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("widgets:detail", kwargs={"pk": self.pk})


class Comment(BaseModel):
    comment = models.TextField()
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="comments"
    )
    widget = models.ForeignKey(
        Widget, on_delete=models.CASCADE, related_name="comments"
    )

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        n = len(self.comment)
        if n > 75:
            return self.comment[:75] + "..."
        return self.comment


class Note(BaseModel):
    text = models.CharField(max_length=128)
    widget = models.ForeignKey(Widget, on_delete=models.CASCADE, related_name="notes")

    def __str__(self):
        return self.text

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('email', 'username',)

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'username',)

widgets/forms.py
from django import forms

from widgets.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("comment",)

    def clean_comment(self):
        data = self.cleaned_data["comment"]
        length = len(data)
        if length > 1024:
            raise forms.ValidationError("The comment is too long.")

        return data

pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = 'pages/home.html'


class AboutPageView(TemplateView):
    template_name = 'pages/about.html'

users/views.py
from django.shortcuts import render

# Create your views here.

widgets/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.core.exceptions import PermissionDenied


from widgets.models import Widget, Comment
from widgets.forms import CommentForm


class WidgetListView(ListView):
    template_name = "widgets/index.html"
    context_object_name = "widgets"
    model = Widget
    paginate_by = 6


class WidgetDetailView(DetailView):
    template_name = "widgets/detail.html"
    context_object_name = "widget"
    model = Widget


class CommentCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = "widgets/comment_form.html"
    model = Widget
    form_class = CommentForm
    success_message = "The comment has been created."

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["widget"] = Widget.objects.get(pk=self.kwargs["pk"])
        context["update"] = False
        return context

    def get_success_url(self):
        return Widget.objects.get(pk=self.kwargs["pk"]).get_absolute_url()

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.widget = Widget.objects.get(pk=self.kwargs["pk"])
        return super().form_valid(form)


class CommentUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = "widgets/comment_form.html"
    model = Comment
    form_class = CommentForm
    success_message = "The comment has been updated."

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["widget"] = Comment.objects.get(pk=self.kwargs["pk"]).widget
        context["update"] = True
        return context

    def get_success_url(self):
        comment = self.get_object()
        return comment.widget.get_absolute_url()

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.widget = Comment.objects.get(pk=self.kwargs["pk"]).widget
        return super().form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.user != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class CommentDeleteView(DeleteView):
    model = Comment
    context_object_name = "comment"
    template_name = "widgets/comment_delete.html"

    def get_success_url(self):
        comment = self.get_object()
        return comment.widget.get_absolute_url()

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.user != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        message = f"The comment has been deleted."
        messages.warning(self.request, message)
        return super().delete(request, *args, **kwargs)

templates/403_csrf.html
{% extends '_base.html' %}

{% block title %}Forbidden (403){% endblock title %}

{% block content %}
<h1>Forbidden (403)</h1>
<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
<title>{% block title %}Widget Collection{% endblock title %}</title>
<meta name="description" content="A framework for launching new Django projects quickly.">
<meta name="author" content="">
<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
<!-- fonts -->
<link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Mono&display=swap" rel="stylesheet">

{% block css %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css">
<link rel="stylesheet" href="{% static 'css/base.css' %}">

{% endblock %}
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="{% url 'widgets:index' %}">Widget Collection</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        {% if user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ user.email }}
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                <a class="dropdown-item" href="{% url 'account_change_password' %}">Change password</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'account_logout' %}">Log out</a>
              </div>
            </li>
          </ul>
        {% else %}
          <form class="form-inline ml-auto">
            <a href="{% url 'account_login' %}" class="btn btn-outline-secondary">Log in</a>
            <a href="{% url 'account_signup' %}" class="btn btn-primary ml-2">Sign up</a>
          </form>
        {% endif %}
      </div>
    </nav>
    {% include "_messages.html" %}
    <main class="container">
      {% block content %}
        <p>Default content...</p>
      {% endblock content %}
    </main>

   <nav class="navbar fixed-bottom navbar-dark bg-dark">
    <a class="navbar-brand" href="#">&copy; Leigh Michael Forrest 2019</a>
  </nav>

  {% block javascript %}
  <!-- Bootstrap JavaScript -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  <!-- 3rd party JavaScript -->

  <!-- Project JS -->
  <script src="{% static 'js/base.js' %}"></script>

  {% endblock javascript %}

</body>
</html>

templates/_messages.html
<div class="container message-container">
{% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div class="alert alert-{{message.tags}}" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    </div>
{% endif %}
</div>

templates/pages/about.html
{% extends '_base.html' %}

{% block title %}About page{% endblock %}

{% block content %}
<h1>About page</h1>
{% endblock content %}

templates/pages/home.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Home page{% endblock title %}

{% block content %}
<h1>Home page</h1>
<img src="{% static 'images/falconx.png' %}" class="img-fluid mx-auto d-block" alt="FalconX launch"/>
{% endblock content %}

templates/partials/_card.html
{% load static %}
<div class="card-container card">
    <img src="{% static 'images/widget.jpeg' %}" alt="">
    <a href="{{ widget.get_absolute_url }}">
        <h2><a href="{{ widget.get_absolute_url }}">{{ widget.name }}</h2>
    </a>
</div>

templates/partials/_comment.html
<div class="card comment-card">
  <div class="card-header bg-secondary text-white">
    {{ comment.user.username }}
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>{{ comment.comment }}</p>
      <footer class="blockquote-footer">{{comment.created_at}}</footer>
    </blockquote>
  </div>
  {% if comment.user == user %}
    <div class="card-footer">
        <a href="{% url 'widgets:comment_update' comment.pk %}"><i class="fa fa-edit"></i></a>
        <a href="{% url 'widgets:comment_delete' comment.pk %}"><i class="fa fa-trash" aria-hidden="true"></i></a>
    </div>  
  {% endif %}
</div>

templates/partials/_pagination.html
{% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}" class="arrow">&#10094;</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }}
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}" class="arrow">&#10095;</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock %} 

templates/widgets/comment_create.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }} {{ widget.name }} Comment
{% endblock title %}

{% block content %}
<p class="text-center">Post your comment for  <a href="{{ widget.get_absolute_url }}">"{{widget.name}}"</a></p>
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Add Comment" class="btn btn-primary">
</form>
{% endblock content %}

templates/widgets/comment_delete.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }} - DELETE {{ comment.widget.name }} Comment
{% endblock title %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete comment for <strong>"{{ comment.widget.name }}"</strong>?</p>
    <input type="submit" value="Delete Comment" class="btn btn-danger">
</form>
{% endblock content %}

templates/widgets/comment_form.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }} {{ widget.name }} Comment
{% endblock title %}

{% block content %}
{% if update %}
    <p class="text-center">Update your comment for  <a href="{{ widget.get_absolute_url }}">"{{widget.name}}"</a></p>
{% else %}
    <p class="text-center">Post your comment for  <a href="{{ widget.get_absolute_url }}">"{{widget.name}}"</a></p>
{% endif %}
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    {% if update %}
        <input type="submit" value="Update Comment" class="btn btn-primary">
    {% else %}
        <input type="submit" value="Add Comment" class="btn btn-primary">
    {% endif %}
</form>
{% endblock content %}

templates/widgets/comment_update.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }} {{ widget.name }} Comment
{% endblock title %}

{% block content %}
<p class="text-center">Update your comment for  <a href="{{ widget.get_absolute_url }}">"{{widget.name}}"</a></p>
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Update Comment" class="btn btn-primary">
</form>
{% endblock content %}

templates/widgets/detail.html
{% extends '_base.html' %}
{% load static %}

{% block title %}{{ block.super }} - {{ widget.name }}{% endblock title %}

{% block content %}
  <div class="row">
  <div class="col-md-5 col-lg-6 mb-4">
    <div class="card">
      <div class="view">
        <img src="{% static 'images/widget.jpeg' %}" class="card-img-top" alt="photo">
        <a href="#">
          <div class="mask rgba-white-slight"></div>
        </a>
      </div>
      <div class="card-body text-center">
        <!--Title-->
        <h4 class="card-title">{{ widget.name }}</h4>
        <!--Text-->
        <ul class="list-group mb-3">
            {% for note in widget.notes.all %}
                <li class="list-group-item">{{ note }}</li>
            {% endfor %}
        </ul>
        {% if user.is_authenticated %}
          <a href="{% url 'widgets:comment_create' widget.pk %}" class="btn btn-primary">Add a Comment</a>
        {% else %}
          Want to comment? <a href="{% url 'account_login' %}">Log In!</a>
        {% endif %}
      </div>

    </div>
    <!--/.Card-->

  </div>
  <!-- Grid column -->

  <!-- Grid column -->
  <div class="col-md-7 col-lg-6 mb-4">

    <!--Card-->
    <div class="card green darken-3 h-100">


      <!--Card content-->
      <div class="card-body text-center">
        <!--Title-->
        <h4 class="card-title white-text">Comments</h4>
        <!--Text-->
        {% if widget.comments.count %}
          {% for comment in widget.comments.all %}
              {% include 'partials/_comment.html' %}
          {% endfor %}
        {% else %}
          <p>There are no comments for this widget.</p>
        {% endif %}
      </div>

    </div>
    <!--/.Card-->
  </div>
  <!-- Grid column -->
  </div>
{% endblock content %}

templates/widgets/index.html
{% extends '_base.html' %}

{% block content %}
<div class="row">
  <div class="card-list">
        {% for widget in widgets %}
          {% include 'partials/_card.html' %}
        {% endfor %}
  </div>
</div>
<div class="pagination-container row">
    {% include 'partials/_pagination.html' %}
</div>
{% endblock content %}